#!/usr/bin/env python

from distutils.core import setup, Extension
import numpy as np

poisson_ext = Extension('poisson', 
    ['poisson/colamd.c',
    'poisson/dasum.c',
    'poisson/daxpy.c',
    'poisson/dcolumn_bmod.c',
    'poisson/dcolumn_dfs.c',
    'poisson/dcopy.c',
    'poisson/dcopy_to_ucol.c',
    'poisson/dgscon.c',
    'poisson/dgsequ.c',
    'poisson/dgsrfs.c',
    'poisson/dgssvx.c',
    'poisson/dgstrf.c',
    'poisson/dgstrs.c',
    'poisson/dlacon.c',
    'poisson/dlamch.c',
    'poisson/dlangs.c',
    'poisson/dlaqgs.c',
    'poisson/dmemory.c',
    'poisson/dmyblas2.c',
    'poisson/dpanel_bmod.c',
    'poisson/dpanel_dfs.c',
    'poisson/dpivotgrowth.c',
    'poisson/dpivotL.c',
    'poisson/dpruneL.c',
    'poisson/dsnode_bmod.c',
    'poisson/dsnode_dfs.c',
    'poisson/dsp_blas2.c',
    'poisson/dsp_blas3.c',
    'poisson/dtrsv.c',
    'poisson/dutil.c',
    'poisson/get_perm_c.c',
    'poisson/heap_relax_snode.c',
    'poisson/idamax.c',
    'poisson/lsame.c',
    'poisson/memory.c',
    'poisson/mmd.c',
    'poisson/poisson.cpp',
    'poisson/relax_snode.c',
    'poisson/sp_coletree.c',
    'poisson/sp_ienv.c',
    'poisson/sp_preorder.c',
    'poisson/superlu_timer.c',
    'poisson/util.c',
    'poisson/xerbla.c'], 
	include_dirs=[np.get_include()], 
	define_macros=[('NO_TIMER', None)])

setup(name='mpfs', 
    version='1.0',
    author='Subhajit Kar',
    author_email='subhajitkar19@gmail.com',
    url='https://github.com/subhk/multi-phase-flow-solver/',
    py_modules=['mpfs.bc', 
	 	'mpfs.domain', 
	 	'mpfs.force',
        'mpfs.ns2d',
        'mpfs.tools',
        'mpfs.writer'],
    ext_package='mpfs',
    ext_modules=[poisson_ext],
    )

